#!/bin/bash
CMD=$1
if [ -z "$1" ]; then
  echo "Kali Docker: Command not found"
  exit 1
fi

docker volume inspect kali-docker > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Mounting Docker volume: kali-docker"
else
  echo "Creating Docker volume: kali-docker"
  docker volume create kali-docker > /dev/null 2>&1
fi

CONTAINER_NAME="kali-$(date +%s | shasum | base64 | head -c 8 ; echo)"
docker run --rm -it \
  -v "kali-docker:/opt" \
  --name $CONTAINER_NAME \
  -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` \
  --hostname $CONTAINER_NAME \
  devxops/kali-docker $CMD