#!/bin/bash
CMD=$1
if [ -z "$1" ]; then
  echo "Kali Docker: Command not found"
  exit 1
fi

docker volume inspect kali-docker > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Mounting Docker volume: kali-docker"
else
  echo "Creating Docker volume: kali-docker"
  docker volume create kali-docker > /dev/null 2>&1
fi

CONTAINER_NAME="kali-$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 8 | head -n 1)"
docker run --rm -it \
  -v "kali-docker:/opt" \
  -v "/etc/localtime:/etc/localtime:ro" \
  --name $CONTAINER_NAME \
  --hostname $CONTAINER_NAME \
  devxops/kali-docker $CMD